
#### general settings

name: Inpaint_ffhq_32_L4K8
use_tb_logger: false
model: Inpaint
gpu_ids: [7]


#### datasets

datasets:
  train:
    name: ffhq
    mode: Inpaint
    img_dataroot: "/home/wcr/datasets/FFHQ/train/" # path to ground-truth imgs
    mask_dataroot: /home/wcr/datasets/mask/testing_mask_dataset # path to external masks, if not provided, rectangular mask will be generated in dataset
    # mask_type: -1 # -1: regular(center hole) | 0: regular(random position) | 1-6: external irregular mask(1 for 1%-10%, 2 for 10%-20% and so on)
    img_size: 32

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 32
    use_flip: true
    use_rot: false

  val:
    name: ffhq
    mode: Inpaint
    img_dataroot: "/home/wcr/datasets/FFHQ/val/" # path to ground-truth imgs
    mask_dataroot: /home/wcr/datasets/mask/testing_mask_dataset # path to external masks, if not provided, rectangular mask will be generated in dataset
    mask_type: 3
    img_size: 32


#### network structures

network_G:
  L: 4
  K: 8
  in_nc: 3
  n_trans: 0
  heat: 1.
  input_size: 32

#### path

path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 2e-4
  beta1: 0.9
  beta2: 0.999
  niter: 300000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps_rel: [0.5, 0.75, 0.9, 0.95]
  lr_gamma: 0.5

  manual_seed: 10

  val_freq: 5000

  weight_decay_G: !!float 1e-5
  gradient_clipping: 10


#### logger

logger:
  print_freq: 200
  save_checkpoint_freq: 10000
