
#### general settings

name: Inpaint_paris_32_L4K10_bk5
use_tb_logger: true
model: Inpaint
gpu_ids: [2]

#### datasets

datasets:
  train:
    name: paris
    mode: Inpaint
    img_dataroot: "/data/zym/paris/paris_train_original/" # path to ground-truth imgs
    mask_dataroot: "/data/zym/mask/testing_mask_dataset/" # path to external masks, if not provided, rectangular mask will be generated in dataset
    # mask_type: -1 # -1: regular(center hole) | 0: regular(random position) | 1-6: external irregular mask(1 for 1%-10%, 2 for 10%-20% and so on)
    img_size: 32
    ksize: 5

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 32
    use_flip: true
    use_rot: false

  val:
    name: paris
    mode: Inpaint
    img_dataroot: "/data/zym/paris/paris_eval_gt/" # path to ground-truth imgs
    mask_dataroot: "/data/zym/mask/testing_mask_dataset/" # path to external masks, if not provided, rectangular mask will be generated in dataset
    mask_type: 3
    img_size: 32
    ksize: 5


#### network structures

network_G:
  L: 4
  K: 10
  in_nc: 3
  n_trans: 0
  heat: 1.
  input_size: 32

#### path

path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~


#### training settings: learning rate scheme, loss

train:
  lr_G: !!float 5e-4
  beta1: 0.9
  beta2: 0.999
  niter: 200000
  warmup_iter: -1  # no warm up

  lr_scheme: MultiStepLR
  lr_steps_rel: [0.5, 0.75, 0.9, 0.95]
  lr_gamma: 0.5

  manual_seed: 10
  
  train_encoder_delay: 50000

  val_freq: 10000

  weight_decay_G: !!float 1e-5
  gradient_clipping: 10


#### logger

logger:
  print_freq: 200
  save_checkpoint_freq: 40000
